/**
 * Mock product data for development
 * Replace this with real API calls once backend is ready
 */

export const mockProducts = [
  {
    id: '1',
    name: 'Minimalist Steel Keychain',
    description: 'Sleek stainless steel keychain with brushed finish. Perfect for everyday carry.',
    price: 24.99,
    salePrice: null,
    image: 'https://images.unsplash.com/photo-1589998059171-988d887df646?w=400&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1589998059171-988d887df646?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1533481405265-e9ce0c044abb?w=600&auto=format&fit=crop&q=80',
    ],
    category: 'Metal',
    stock: 50,
    isFeatured: true,
    isNew: false,
    rating: 4.8,
    reviews: 124,
    features: [
      'Premium stainless steel construction',
      'Brushed matte finish',
      'Compact and lightweight',
      'Rust-resistant coating',
    ],
  },
  {
    id: '2',
    name: 'Leather Loop Keychain',
    description: 'Handcrafted genuine leather keychain with brass hardware.',
    price: 34.99,
    salePrice: 29.99,
    image: 'https://images.unsplash.com/photo-1591561954557-26941169b49e?w=400&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1591561954557-26941169b49e?w=600&auto=format&fit=crop&q=80',
    ],
    category: 'Leather',
    stock: 30,
    isFeatured: true,
    isNew: true,
    rating: 4.9,
    reviews: 87,
    features: [
      'Full-grain leather',
      'Hand-stitched details',
      'Solid brass ring',
      'Ages beautifully over time',
    ],
  },
  {
    id: '3',
    name: 'Carbon Fiber Keychain',
    description: 'Ultra-lightweight carbon fiber keychain with titanium ring.',
    price: 49.99,
    salePrice: null,
    image: 'https://images.unsplash.com/photo-1513828583688-c52646db42da?w=400&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1513828583688-c52646db42da?w=600&auto=format&fit=crop&q=80',
    ],
    category: 'Metal',
    stock: 25,
    isFeatured: false,
    isNew: true,
    rating: 5.0,
    reviews: 45,
    features: [
      'Aerospace-grade carbon fiber',
      'Titanium split ring',
      'Ultra-lightweight design',
      'Scratch-resistant surface',
    ],
  },
  {
    id: '4',
    name: 'Classic Brass Keychain',
    description: 'Timeless solid brass keychain with vintage patina finish.',
    price: 19.99,
    salePrice: null,
    image: 'https://images.unsplash.com/photo-1589998059171-988d887df646?w=400&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1589998059171-988d887df646?w=600&auto=format&fit=crop&q=80',
    ],
    category: 'Metal',
    stock: 100,
    isFeatured: true,
    isNew: false,
    rating: 4.7,
    reviews: 203,
    features: [
      'Solid brass construction',
      'Vintage patina finish',
      'Classic design',
      'Develops unique character',
    ],
  },
  {
    id: '5',
    name: 'Paracord Keychain',
    description: 'Durable paracord keychain in multiple colors. Outdoor ready.',
    price: 14.99,
    salePrice: 12.99,
    image: 'https://images.unsplash.com/photo-1533481405265-e9ce0c044abb?w=400&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1533481405265-e9ce0c044abb?w=600&auto=format&fit=crop&q=80',
    ],
    category: 'Custom',
    stock: 75,
    isFeatured: false,
    isNew: false,
    rating: 4.5,
    reviews: 156,
    features: [
      '550 paracord material',
      'Weather-resistant',
      'Multiple color options',
      'Emergency rope backup',
    ],
  },
  {
    id: '6',
    name: 'Titanium Carabiner Keychain',
    description: 'Premium titanium carabiner with secure locking mechanism.',
    price: 39.99,
    salePrice: null,
    image: 'https://images.unsplash.com/photo-1589998059171-988d887df646?w=400&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1589998059171-988d887df646?w=600&auto=format&fit=crop&q=80',
    ],
    category: 'Metal',
    stock: 40,
    isFeatured: true,
    isNew: false,
    rating: 4.9,
    reviews: 98,
    features: [
      'Grade 5 titanium',
      'Screw-lock gate',
      'Corrosion-resistant',
      'Rated for 100kg',
    ],
  },
  {
    id: '7',
    name: 'Wooden Keychain',
    description: 'Handcrafted walnut wood keychain with natural oil finish.',
    price: 22.99,
    salePrice: null,
    image: 'https://images.unsplash.com/photo-1513828583688-c52646db42da?w=400&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1513828583688-c52646db42da?w=600&auto=format&fit=crop&q=80',
    ],
    category: 'Custom',
    stock: 20,
    isFeatured: false,
    isNew: true,
    rating: 4.6,
    reviews: 34,
    features: [
      'Solid walnut wood',
      'Natural oil finish',
      'Unique grain pattern',
      'Eco-friendly material',
    ],
  },
  {
    id: '8',
    name: 'Minimalist Aluminum Keychain',
    description: 'Anodized aluminum keychain with sleek modern design.',
    price: 16.99,
    salePrice: null,
    image: 'https://images.unsplash.com/photo-1533481405265-e9ce0c044abb?w=400&auto=format&fit=crop&q=80',
    images: [
      'https://images.unsplash.com/photo-1533481405265-e9ce0c044abb?w=600&auto=format&fit=crop&q=80',
    ],
    category: 'Minimalist',
    stock: 60,
    isFeatured: false,
    isNew: false,
    rating: 4.4,
    reviews: 112,
    features: [
      'Anodized aluminum',
      'Multiple color options',
      'Lightweight design',
      'Scratch-resistant coating',
    ],
  },
]